traPtitech/traQ-bot-console

src/views/BotDetail.vue, src/views/CreateBot.vue
=> 無効なエンドポイントURLエラーの表示

src/views/ClientDetail.vue
=> clientIdのコピーボタンが動作しないのを修正

src/views/BotDetail.vue, src/views/ClientDetail.vue, src/views/WebhookDetail.vue
=> 「コピーしました」表示 close #13

package.json, src/api.js, src/layouts/Default.vue, src/store/index.js, src/views/BotDetail.vue, src/views/ClientDetail.vue, src/views/Clients.vue, src/views/CreateBot.vue, src/views/CreateClient.vue, src/views/CreateWebhook.vue, src/views/WebhookDetail.vue, src/views/Webhooks.vue, yarn.lock
=> node-traqで書き換え

src/views/Home.vue
=> ダッシュボードの作成

package.json, yarn.lock
refs #102 #104 #105 #106 #107 #108
=> Bump @vue/cli from 4.4.6 to 4.5.2

package.json, yarn.lock
refs #111 #115 #116 #117 #119 #120
=> Bump @vue/cli from 4.5.2 to 4.5.4

package.json, yarn.lock
refs #130 #131 #132 #133 #134 #135
=> Bump @vue/cli from 4.5.4 to 4.5.6

package.json, yarn.lock
close #161 
close #164 
close #165 
close #168 
close #170
=> Bump @vue/cli from 4.5.7 to 4.5.8

package.json, yarn.lock
close #182 
close #183 
close #185 
close #186 
close #188 
close #189
=> Bump @vue/cli from 4.5.8 to 4.5.9

package.json, yarn.lock
close #219 
close #221 
close #222 
close #223 
close #224 
close #226
=> Bump @vue/cli from 4.5.9 to 4.5.10

package.json, yarn.lock
close #265 
close #267 
close #268 
close #269 
close #270 
close #271
=> Bump @vue/cli from 4.5.10 to 4.5.12

package.json, yarn.lock
close #296 
close #297 
close #298 
close #299 
close #301 
close #302
=> Bump @vue/cli from 4.5.12 to 4.5.13

src/views/BotDetail.vue
https://github.com/traPtitech/traQ/pull/1207
こちらの方の変更が入ったらお願いします 🙏
=> Update datetime field casing

src/docs/bot/traq-api.md
fixes #293 
いきなり404来てびっくりしたので、good-first-issueだけど直しちゃった
traQ担当だしいいですよね(言い訳)
=> traQ API リファレンスへのリンクを更新

src/views/BotDetail.vue, src/views/CreateBot.vue
こんな感じかなという最低限のを一応
よろしくお願いします :fastparrot:
closes #399
=> Bot modeの変更 / logのresultを見る

src/docs/bot/http-server.md, src/docs/bot/ws-server.md
=> 📚 add bot library links

src/views/BotDetail.vue
=> hide-selectionを外して選択したチャンネル名が見えるように

src/docs/bot/events/index.md, src/docs/bot/events/user-group.md
https://github.com/traPtitech/traQ/pull/1894 に対応するやつです
=> BOTイベントのドキュメントを追加

src/botEvents.js
https://github.com/traPtitech/traQ-bot-console/pull/514 の続き
アプリUI側に反映させるのを忘れていました。動作確認はできてないですが、ざっと読んだ限りではこれで良さそう
=> BOTイベントの追加をアプリに反映

src/docs/bot/events/index.md, src/router/index.js
ユーザーグループのドキュメントの変更が反映されていなかった。
- ドキュメントのパスが間違っていた
- importの設定を書く必要があった
=> Fix user-group doc

src/botEvents.js, src/docs/bot/events/user.md
https://github.com/traPtitech/traQ/pull/2266 に伴う対応
ブランチ名間違えました
=> USER_ACTIVATED botイベントを追加
